#!/bin/sh
while [ 1 ]
do
	IP_ADDRESS=`hostname -I | xargs | awk '{print $1}'`
	CODE=`ifconfig | grep ether | head -n 1 | awk '{print $2;}' | awk -F":" '{print $4 $5 $6}'`
	NAME="Shroom%20Pi%20$CODE"
	URL="http%3A%2F%2F$IP_ADDRESS"
	curl -X POST https://wheresmypi.herokuapp.com?$NAME=$URL
	if [ $? -ne 0 ]
	then
		sleep 1m
	else
		echo IP address successfully update on wheresmypi
		sleep 30m
	fi
done


